steps:
  # Step 0: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-t'
      - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:develop'
      - '.'

  # Step 1: Push da imagem com SHORT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:$SHORT_SHA'

  # Step 2: Push da imagem com tag develop
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:develop'

  # Step 3: Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_CLOUD_RUN_SERVICE}'
      - '--image'
      - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/agrogame/agrogame-repo/agrogame-homepage:develop'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
