steps:
  - name: 'node:20'  # Use a versão do Node que seu projeto utiliza
    entrypoint: 'npm'
    args: ['install']
    id: 'Install Dependencies'

  # 3. Roda o build de produção para garantir que a aplicação compila
  # Isso gera os arquivos estáticos na pasta 'dist/' ou 'build/', validando o código.
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'Build Application'

# A seção 'options' para garantir que os logs funcionem com a conta de serviço
options:
  logging: CLOUD_LOGGING_ONLY

