steps:
  # Step 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-t'
      - '$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:$SHORT_SHA'
      - '-t'
      - '$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:develop'
      - '.'

  # Step 2: Push da imagem com SHORT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:$SHORT_SHA'

  # Step 3: Push da imagem com tag develop
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:develop'

  # Step 4: Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/run'
    args:
      - 'deploy'
      - '${_CLOUD_RUN_SERVICE}'
      - '--image'
      - '${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - '$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:$SHORT_SHA'
  - '$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:develop'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
